name: StrengthLimit
main: dev.ender.strengthlimit.StrengthLimit
author: EnderTheCoder
version: 1.0
depend: [PlaceholderAPI]

commands:
  resetstrength:
    aliases: rs
    permission: strengthlimit.reset
  addstrength:
    aliases: as
    permission: strengtthlimit.add
permissions:
  strengthlimit.reset:
    default: true
    description: 重置体力权限
  strengtthlimit.add:
    default: op
    description: 增加体力权限
  strengtthlimit.vip:
    default: false
    description: VIP体力权限